
// This file is automatically generated. Do not edit it directly.
import { createSupabaseClient } from '@/lib/supabase-env';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createSupabaseClient();
